name: Build and Analyze

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze MERN App
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      # Set up Node.js (adjust version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies (for both frontend and backend)
      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      # Run tests (optional, but recommended)
      - name: Run Tests
        run: |
          cd backend && npm test
          cd ../frontend && npm test

      # Run SonarQube analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=my-mern-app
            -Dsonar.organization=my-org  # Remove this if not using SonarCloud
            -Dsonar.sources=backend,frontend
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
